version: '3.4'
services:
  swoft:
    image: swoft/swoft
#    for local develop
    command: php -S 127.0.0.1:13300
    container_name: swoft-learn
    environment:
      - APP_ENV=dev
      - TIMEZONE=Asia/Shanghai
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "17306:17306"
    volumes:
       - ./:/var/www/swoft
#       - ./:/var/www/swoft:delegated
#      - ./:/var/www/swoft:cached
      # - ./runtime/ng-conf:/etc/nginx
      # - ./runtime/logs:/var/log

  mysql:
    image: mysql
    container_name: mysql-learn
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - ./runtime/data/mysql:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  redis:
    container_name: redis-learn
    image: redis
    ports:
      - "6380:6379"
    sysctls:
      net.core.somaxconn: 65535
    restart: always
